### ISSUE TITLE
Support api/v3/simple endpoints

### ISSUE THREAD

**Issue by patrykwozinski** [patrykwozinski/gecko#1]
![Screenshot 2021-04-16 at 09 16 54](https://user-images.githubusercontent.com/17459288/114986610-7ded8a80-9e94-11eb-84a8-127cf7c254b9.png)

### Endpoints to-do
- [x] `api/v3/simple/price` #3 
- [x] `api/v3/token_price/{id}` #4
- [x] `api/v3/simple/supported_vs_currencies` #5

### Remember
- [x] Update list of supported endpoints in `README.md`
